version: '3.8'
services:
  web:
    depends_on:
      - db
    build:
      context: .
    hostname: user-service
    container_name: user-service
    ports:
      - 80:${PORT:-6969}
    networks:
      - backend
    environment:
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:-postgres}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE:-userdb}
      - PORT=${PORT:-6969}
      #restart_policy:
      #condition: on-failure
  db:
    hostname: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userdb
    ports:
      - 5432:5432
    networks:
      - backend
#volumes:


networks:
  backend:
    driver: bridge