version: '3.8'
services:
  web:
    depends_on:
      - db
    build:
      context: .
    hostname: user-service
    container_name: user-service
    ports:
      - 80:8080
    environment:
      - PGUSER=${PGUSER:-postgres}
      - POSTGRES_PASSWORD=${PGPASSWORD:-postgres}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE:-user-db}
        #    deploy:
        #restart_policy:
      #condition: on-failure
  db:
    hostname: db
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata: